apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: todo-network-policy
  namespace: todo-app
spec:
  podSelector:
    matchLabels:
      app: todo-mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: todo-app
    ports:
    - protocol: TCP
      port: 3306
